### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by gandalfsaxe** [kejadlen/giphy.alfredworkflow#10]
When I search for any gif, it just goes to the default fallback search searches:

![image](https://user-images.githubusercontent.com/12127864/37555208-50329f2c-29e4-11e8-975a-4d7ecfdb9b3c.png)

and then:

![image](https://user-images.githubusercontent.com/12127864/37555211-56f04058-29e4-11e8-837c-6e2a0eae4547.png)

**Comment by kejadlen** [comment]
Can you take a peek in the Alfred workflow debugger to see what it says? https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by gandalfsaxe** [comment]
Ah the newest release works. I downloaded an old version from http://www.packal.org/workflow/giphy - perhaps that should be updated :)

**Comment by kejadlen** [comment]
Ah, thanks - will update Packal.
