### ISSUE TITLE
Display GIF animation

### ISSUE THREAD

**Issue by gregschwartz** [kejadlen/giphy.alfredworkflow#11]
I love the convenience of an Alfred plugin! But having to open and close it multiple times to find the animated GIF I want doesn't really work :\

Is there a way to show the animations within the Alfred window, preferably at a larger size? (I suspect not, but asking just in case.)

**Comment by kejadlen** [comment]
Yeah, I don't think there's a good way of doing this within Alfred short of launching into another application (in which case it's probably easier to just to do that), but I'm definitely open to ideas otherwise!
