### ISSUE TITLE
Specify Number of Results

### ISSUE THREAD

**Issue by invious** [kejadlen/giphy.alfredworkflow#15]
I see you hardcoded 9 results, can we get an extra arg to specify how many to return?

I can't read or compile the rust code myself :/

**Comment by kejadlen** [comment]
Would be slightly inconvenient as an extra arg, since then searching for “number 1” would be ambiguous. Are you looking to be able to change it per query, or would setting the number of results as an overall workflow option be sufficient?

**Comment by elisavetsky** [comment]
can you make the results scrollable? 9 is definitely not enough.

**Comment by kejadlen** [comment]
Added a `LIMIT` environment variable you can set in the workflow to get more results in [v3.2.2](https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v3.2.2).
