### ISSUE TITLE
[Breaking] ERROR: input.scriptfilter

### ISSUE THREAD

**Issue by diegolamanno** [kejadlen/giphy.alfredworkflow#18]
I am not sure if this is just for me but I haven't been able to use the workflow since the latest update.

I get this from the debugger.

![Screen Shot 2019-05-04 at 1 09 53 PM](https://user-images.githubusercontent.com/4256064/57182554-3c61a180-6e6e-11e9-986a-f6dfd698a6c8.png)

Would like to help but I am not familiar at all with Rust.

Thanks for the amazing workflow.

**Comment by kejadlen** [comment]
What version are you running?

**Comment by kejadlen** [comment]
Dupe of #17?

**Comment by kejadlen** [comment]
Please re-open if this still happens on [v3.2.1](https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v3.2.1).

**Comment by diegolamanno** [comment]
I can say it is solved after the update. Working as expected! Thanks @kejadlen
