### ISSUE TITLE
Error: missing field `data` at line 1 column 37 when using plugin

### ISSUE THREAD

**Issue by gronso** [kejadlen/giphy.alfredworkflow#19]
Any ideas what might be going on?  This is the full error:

[2019-05-16 08:58:11][ERROR: input.scriptfilter] Code 1: Error: missing field `data` at line 1 column 37

**Comment by gronso** [comment]
Here is log with All information:

> [2019-05-16 09:00:04][input.scriptfilter] Queuing argument 'test'
> [2019-05-16 09:00:05][input.scriptfilter] Script with argument 'test' finished
> [2019-05-16 09:00:05][ERROR: input.scriptfilter] Code 1: Error: missing field `data` at line 1 column 37

**Comment by gronso** [comment]
This is on a Mac version 10.12.6 and alfred version 3.8.1 [961]

**Comment by kejadlen** [comment]
What version of the workflow are you using? (Maybe a dupe of #17?)

**Comment by gronso** [comment]
It was 3.2.1.  I downloaded from the alfred site - I updated from the version here and now it works.  Thanks!
