### ISSUE TITLE
Clear installation instructions needed.

### ISSUE THREAD

**Issue by politicus** [kejadlen/giphy.alfredworkflow#20]
Hi!

Thanks for your very nice workflow! 

I had to re-install mine as the version I had was not working anymore. 

Found you on Github, downloaded the workflow then got stuck as I didn't know what to do with the files I had. 

Downloaded your workflow from packal.org. Then, I was able to install the workflow.

**Comment by kejadlen** [comment]
Just to confirm, you downloaded [this release](https://github.com/kejadlen/giphy.alfredworkflow/releases/download/v3.2.1/Giphy.alfredworkflow) and double-clicking it didn't work to install it?

**Comment by politicus** [comment]
The link in your answer let me download an .alfredworkflow file and install the workflow after double clicking on it. The file I downloaded on github via this [link](https://github.com/kejadlen/giphy.alfredworkflow/archive/master.zip), once unarchived, was a collection of files/folders without any .alfredworkflow file.

**Comment by kejadlen** [comment]
There's a link to the releases already in the [README](https://github.com/kejadlen/giphy.alfredworkflow#installation) - if you have any further suggestions for improvements to this section, PRs are welcome!
