### ISSUE TITLE
When viewing pasted GIF from iMessage on iOS the GIF doesn't animate.

### ISSUE THREAD

**Issue by elisavetsky** [kejadlen/giphy.alfredworkflow#22]
It seems as though what we copy is just a JPEG file, the gif is running fine on my mac when I paste it into iMessage, but when i switch over to my phone's iMessage, it reads as a JPEG picture and doesn't animate. Huh???

**Comment by stacksjb** [comment]
I'm having this same issue. I want to use this to copy/paste an image into mail, but it appears to be copy/pasting a screenshot or TIFF image, not the gif. Going to the URL, downloading the file, and inserting it is a pain.

**Comment by jalogisch** [comment]
Dup from: https://github.com/kejadlen/giphy.alfredworkflow/issues/2
