### ISSUE TITLE
Developer cannot be verified

### ISSUE THREAD

**Issue by megaroeny** [kejadlen/giphy.alfredworkflow#23]
My MacBook settings are preventing me from using this. Can you look into updating this in some way? The other Workflows I use do not have this issue. Thanks!

![image](https://user-images.githubusercontent.com/1559447/85173117-7ba0ac80-b240-11ea-8c71-0983503bbe19.png)

**Comment by megaroeny** [comment]
I just updated to the latest version too, and same thing. ☹️

**Comment by kejadlen** [comment]
Does this happen when you run the workflow? You may need to go through these steps here: https://github.com/deanishe/alfred-sublime-text/issues/20#issuecomment-539578934

Unfortunately, I'm not sure if there's a way to notarize a command line app without making it go through an installer process to avoid jumping through these hoops.

**Comment by megaroeny** [comment]
@kejadlen ah yeah it might be that! I'll give it a try this weekend and follow-up, thanks!

**Comment by megaroeny** [comment]
@kejadlen that worked! Thanks! I had to tell macOS to "Open anyway" after going through those steps.
