### ISSUE TITLE
Feature request: Add a way to open the searched term in a browser window at Giphy.com

### ISSUE THREAD

**Issue by galligan** [kejadlen/giphy.alfredworkflow#25]
It would be nice as an alternative to just picking the GIF from within the Alfred window, to pop over to the Giphy site with the search text pre-populated. This would help in scenarios when I can't really pick the perfect GIF to send.

**Comment by kejadlen** [comment]
Released in [4.0.2](https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v4.0.2)
