### ISSUE TITLE
remove quicklook cause its already there

### ISSUE THREAD

**Issue by chrisgrieser** [kejadlen/giphy.alfredworkflow#26]
Great workflow! One thing to improve comes to my mind. Using Alfred's built in functionality to quicklook also does the job: pressing shift. 

Quick looking this way is also preferable because you can just press shift again and go back to the Alfred search, when you do not like the gif. Pressing enter in the current workflow copies the URL, but also opens a quicklook-preview, but previewing this way is quite inefficient. When you change your mind because you dont like the gif, you have to Press Esc and then cmd+space again and scroll down. Just pressing shift again is much easier.

Removing the preview from "enter" would also mac the process quicker if you already know the gif and just wanna copy its URL quickly.

**Comment by kejadlen** [comment]
Thanks, that's a way better experience! Released 4.0.0, which should have this change.
