### ISSUE TITLE
Alfred 3

### ISSUE THREAD

**Issue by infn8** [kejadlen/giphy.alfredworkflow#3]
Seems not to work.  the search previews are not gifs (they don't move) and the result of choosing any of them is a preview window but no clipboard entry

**Comment by kejadlen** [comment]
Since Alfred doesn't support animated GIFs for result thumbnails, the base action is to preview the GIF and cmd+return copies the link to the GIF.

**Comment by infn8** [comment]
What about an option that does both?  base action previews AND copies the link.  CMD option copies the link.

it's just now to se a preview and get the link is 2 actions.  maybe alt+return to do both?  I don't mind wiping the clipboard contents a few times.  i never keep anything important there for longer than 10-20 seconds anyways.  but when i see the preview i like i want to just proceed to pasting. 

thoughts?

also thanks for a great workflow and the quick response.  this is totally awesome.

**Comment by kejadlen** [comment]
Oh, I like that idea.

**Comment by infn8** [comment]
Cool. Can I help at all?

**Comment by megaroeny** [comment]
So, right now it does everything correct for me, minus copying the URL. Thanks for making this, so awesome!! More people need to know about it 👍 

See issue I opened #4

**Comment by kejadlen** [comment]
Added the ability to copy the gif itself when using cmd as the action modifier.
