### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by avoll89** [kejadlen/giphy.alfredworkflow#30]
When I use the keyword giphy and put in a search term, nothing happens. Is there an additional setup step I need to take that's not listed in the readme? Thanks!

**Comment by kejadlen** [comment]
Looks like Giphy's API has changed a bit - can you try the latest release and see if that works? https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v4.0.3

**Comment by DesertRec** [comment]
Works for me now, version still say 4.0.2 in Alfred.

<img width="293" alt="Screenshot 2022-05-25 at 05 10 36" src="https://user-images.githubusercontent.com/15858702/170171966-69b905f0-34dc-4c8e-91c6-12a8ce3191ed.png">

**Comment by kejadlen** [comment]
Great, will address the version mismatch as part of #31.

**Comment by avoll89** [comment]
I downloaded the newest version but it still doesn't work for me. @kejadlen 

https://user-images.githubusercontent.com/105996436/170359322-444b49f8-39c7-43f1-9b17-6798e378351b.mp4

**Comment by kejadlen** [comment]
Can you take a look in the workflow debugger and see if there's any info there? https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by avoll89** [comment]
> https://www.alfredapp.com/help/workflows/advanced/debugger/

@kejadlen When I run the debugger, I just get this:
[08:49:15.618] Logging Started...
[08:49:25.741] Giphy[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A6C7FC9E-EA20-40D9-AEE9-2B843496ED53%3E63178F25-7718-4704-A5A4-A092D70B1D7A)] Queuing argument 'bat'

And then Alfred crashes.

**Comment by kejadlen** [comment]
Oh, curious. Alfred crashing is a bit out of my purview. Unfortunately, you may need to open an issue up with Alfred on the crashing so you can see what's causing the Giphy workflow to fail.
