### ISSUE TITLE
Version # wrong in Alfred - 4.0.3 release

### ISSUE THREAD

**Issue by megaroeny** [kejadlen/giphy.alfredworkflow#31]
https://github.com/kejadlen/giphy.alfredworkflow/blob/225c3e4568c315bfd46f552a0423496238013e21/workflow/info.plist#L612

Noticed it still shows as v`4.0.2` in Alfred. Guessing it's from this file/line?

**Comment by kejadlen** [comment]
Should be fixed in v4.0.4.
