### ISSUE TITLE
Consider adding a license 

### ISSUE THREAD

**Issue by d1egoaz** [kejadlen/giphy.alfredworkflow#32]
👋 I wonder if you'd like to provide a license to this repository https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

as today, this is the current state:
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. 

Thanks

**Comment by kejadlen** [comment]
Thanks!
