### ISSUE TITLE
Quick Look not working?

### ISSUE THREAD

**Issue by numeric123** [kejadlen/giphy.alfredworkflow#38]
Hello, I'm not sure if this is actually an issue or if I might be missing something. I can see on the main page it states `Actioning on a search item will preview the gif using Quick Look and copy the direct URL of the gif to the clipboard.` but after trying several button combinations (including the space keys which usually opens Quick Look) I can't seem preview any of the gifs.

Do this sound like a bug?

Thanks

**Comment by kejadlen** [comment]
What happens if you press shift?

**Comment by numeric123** [comment]
Ah thanks Kejadlen! That was it! Apologies I must have misunderstood originally but everything is working perfectly now.
