### ISSUE TITLE
No results on Alfred v3.4.1 (860)

### ISSUE THREAD

**Issue by zvaehn** [kejadlen/giphy.alfredworkflow#7]
![image](https://user-images.githubusercontent.com/5555821/29609467-9abf5c90-87f7-11e7-9d54-56e53cf1cd53.png)

**Comment by kejadlen** [comment]
Can you check the debug log for the workflow and see what it says?

https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by zvaehn** [comment]
```ruby
Starting debug for 'Giphy'

[2017-08-24 11:53:59][input.scriptfilter] Queuing argument 'wow'
[2017-08-24 11:53:59][input.scriptfilter] Script with argument '(null)' finished
[2017-08-24 11:53:59][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alphred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from giphy.rb:5:in `<main>'
```

**Comment by kejadlen** [comment]
How did you install the workflow?

**Comment by zvaehn** [comment]
I doubleclicked it 😝

**Comment by kejadlen** [comment]
I mean, what version? 😛 

The curious part is that your Alfred is using Ruby 2.3?

**Comment by zvaehn** [comment]
I am running "ruby 2.3.3p222 (2016-11-21 revision 56859)
[universal.x86_64-darwin17]”.

Best

**Comment by kejadlen** [comment]
That would be the problem - this expects users to be using system Ruby (2.0). If you go to the workflow directory and run `bundle install --standalone --path vendor/bundle --without development test`, that will install the gems for 2.3 such that the workflow will be able to use them.

**Comment by zvaehn** [comment]
After i installed bundler with `gem install bundler
` i was able to run the mentioned command and it works now! Thank you :) 

![image](https://user-images.githubusercontent.com/5555821/29739908-ffc8de46-8a49-11e7-83f8-05e5a69e1907.png)
