### ISSUE TITLE
v3.0.1 is not installable

### ISSUE THREAD

**Issue by roest01** [kejadlen/giphy.alfredworkflow#8]
Is there any trick to install the v3.0.1 or v2.0.4.travis.3 ?

v2.0.3 is working on Alfred v3.4.1

![3wcrxx](https://user-images.githubusercontent.com/2870718/30819069-e1108710-a21d-11e7-9fa9-a4c6b3e2b5fd.gif)

**Comment by kejadlen** [comment]
Thanks for the bug report - I screwed up those releases, [3.0.4](https://github.com/kejadlen/giphy.alfredworkflow/releases/download/v3.0.4/giphy.alfredworkflow) should work now.
