### ISSUE TITLE
Unable to run task

### ISSUE THREAD

**Issue by selrond** [kejadlen/giphy.alfredworkflow#9]
Just downloaded the latest release [v3.0.4] and this jumped out on me upon initial run:

![image](https://user-images.githubusercontent.com/6603389/30980795-8d993e8a-a482-11e7-8bde-a24a555c4c5a.png)

**Comment by heyflorin** [comment]
Just came here to report the same thing. I thought it was related to my cloud synced alfredpreferences file but it looks like you're using default.

**Comment by kejadlen** [comment]
Huh, that's strange... could you go to that folder and check to see if there's a `giphy-alfredworkflow` file in there? If there is, if you're familiar w/the terminal, could you check if it's executable? Should look something like this:

```
❯ ls -l
.rw-r--r--@  24k alpha 27 Sep  8:09 0744A6DC-F5C1-4D81-8056-8C281A5494D2.png
.rwxr-xr-x@ 2.4M alpha 27 Sep  8:24 giphy-alfredworkflow
.rw-r--r--@  24k alpha 27 Sep  8:09 icon.png
.rw-r--r--@ 6.1k alpha 28 Sep 19:58 info.plist
```

**Comment by selrond** [comment]
@kejadlen this is the output - looks same:

```shell
-rw-r--r--@ 0744A6DC-F5C1-4D81-8056-8C281A5494D2.png
-rwxr-xr-x@ giphy-alfredworkflow
-rw-r--r--@ con.png
-rw-r--r--@ info.plist
```

**Comment by kejadlen** [comment]
Oops, that binary was built for Linux. I rolled a [new release](https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v3.0.6) that should work on OS X. Sorry about that!

**Comment by heyflorin** [comment]
![200w_d](https://user-images.githubusercontent.com/3247722/31027390-eb904264-a4fe-11e7-95de-41d136b1b18e.gif)

**Comment by kejadlen** [comment]
Let me know if this still doesn't work in 3.0.6!
